sonar.projectKey=Ghofranez_pipeline-test
sonar.organization=ghofranez
sonar.host.url=https://sonarcloud.io

# ── Sources ──────────────────────────────
sonar.sources=backend,frontend/src
sonar.exclusions=\
  **/node_modules/**,\
  **/.venv/**,\
  **/venv/**,\
  **/__pycache__/**,\
  **/frontend/dist/**,\
  **/frontend/coverage/**,\
  **/*.min.js

# ── Tests ────────────────────────────────
sonar.tests=backend/app/tests,frontend/src
sonar.test.inclusions=\
  backend/app/tests/**,\
  frontend/src/**/*.test.tsx,\
  frontend/src/**/*.spec.tsx

# ── Coverage ─────────────────────────────
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# ── Langages ─────────────────────────────
sonar.python.version=3.12
sonar.language=py,ts,tsx