soft-fail: false
directory: "."
skip-check:
  - CKV_AWS_20
  - CKV_K8S_21
  - CKV_DOCKER_2      # ← HEALTHCHECK déjà présent dans nos dockerfiles
  - CKV_DOCKER_3      # ← USER non-root déjà présent
skip-path:
  - tests
  - frontend/node_modules
  - frontend/dist
  - backend/.venv
  - docs