FROM golang:1.25-alpine AS nuclei-builder

RUN apk add --no-cache git gcc musl-dev

RUN git clone --depth 1 --branch v3.3.9 \
    https://github.com/projectdiscovery/nuclei.git /nuclei

WORKDIR /nuclei

# x/crypto max compatible Go 1.25 (< v0.52.0 qui exige Go 1.25+)
RUN go get golang.org/x/crypto@v0.35.0 && \
    go get golang.org/x/net@v0.36.0 && \
    go get golang.org/x/oauth2@v0.27.0 && \
    go get github.com/golang-jwt/jwt/v4@v4.5.2 && \
    go get github.com/golang-jwt/jwt/v5@v5.2.2 && \
    go get github.com/buger/jsonparser@v1.1.2 && \
    go get github.com/antchfx/xpath@v1.3.6 && \
    go get github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3 && \
    go get github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.7.8 && \
    go mod tidy

RUN go build -o /usr/local/bin/nuclei ./cmd/nuclei/


FROM python:3.11-alpine

WORKDIR /app

COPY --from=nuclei-builder /usr/local/bin/nuclei /usr/local/bin/nuclei
RUN chmod +x /usr/local/bin/nuclei

RUN apk add --no-cache wget curl ca-certificates unzip git

RUN adduser -D celeryuser && \
    mkdir -p /home/celeryuser/nuclei-templates && \
    chown -R celeryuser:celeryuser /home/celeryuser && \
    chown -R celeryuser:celeryuser /app

COPY requirements.txt .
RUN pip install --no-cache-dir --timeout=300 --retries=5 -r requirements.txt
RUN pip install --upgrade setuptools wheel

ENV NUCLEI_TEMPLATES_PATH=/home/celeryuser/nuclei-templates

USER celeryuser
COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]