FROM golang:1.23-alpine AS nuclei-builder
RUN apk add --no-cache git gcc musl-dev
RUN git clone --depth 1 --branch v3.3.9 \
    https://github.com/projectdiscovery/nuclei.git /nuclei
WORKDIR /nuclei
RUN go build -o /usr/local/bin/nuclei ./cmd/nuclei/

FROM python:3.11-alpine
WORKDIR /app
COPY --from=nuclei-builder /usr/local/bin/nuclei /usr/local/bin/nuclei
RUN chmod +x /usr/local/bin/nuclei
RUN apk add --no-cache wget curl ca-certificates unzip git
RUN adduser -D celeryuser && \
    mkdir -p /home/celeryuser/nuclei-templates && \
    chown -R celeryuser:celeryuser /home/celeryuser && \
    chown -R celeryuser:celeryuser /app
COPY requirements.txt .
RUN pip install --no-cache-dir --timeout=300 --retries=5 -r requirements.txt
RUN pip install --upgrade setuptools wheel
ENV NUCLEI_TEMPLATES_PATH=/home/celeryuser/nuclei-templates
USER celeryuser
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]